create database if not exists finance_db;
use finance_db;

DROP TABLE IF EXISTS t_user_info;
CREATE TABLE t_user_info(
	Fuid			bigint(20) 		AUTO_INCREMENT	COMMENT '用户内部ID',
	Fuser_name		varchar(128)	NOT NULL 	COMMENT '注册的用户名（编码后保存）',
	Ftrue_name		varchar(128)	NOT NULL 	COMMENT '用户真实姓名',
	Fpwd			varchar(64)		NOT NULL 	COMMENT '用户注册时的登陆密码（hash后保存）',
	Fpay_pwd		varchar(64)		default null 	COMMENT '用户的支付操作密码（hash后保存）',
	Fsex			smallint		NOT NULL 	COMMENT '性别1男 2 女',
    Fmobile			varchar(32)		NOT NULL 	COMMENT '手机号',
    Femail			varchar(64)		default null 	COMMENT '邮箱地址',
    Fphone			varchar(32)		default NULL	COMMENT '固定电话，默认为空',
    Fcre_type		smallint		default NULL  	COMMENT '证件类型 1身份证',
    Fcre_id			varchar(255)	default NULL 	COMMENT '证件号',
	Fstate			smallint		default '1' 	COMMENT '用户状态 1正常2冻结3注销',
    Flstate			smallint		default '1' 	COMMENT '物理逻辑状态（logical state）1有效2无效',
    Fip				varchar(32)		NOT NULL 	COMMENT '用户注册时的IP',    
    Fuser_seed		varchar(64)		NOT NULL 	COMMENT '用户种子信息',    
    Fsign			varchar(32)		NOT NULL 	COMMENT '数据签名',    
	Fcreate_time    datetime 		NOT NULL	COMMENT '创建时间',    
	Fmodify_time    datetime 		NOT NULL	COMMENT '最后修改时间',    
    Flogin_ip		varchar(32) 	NOT NULL 	COMMENT '用户最后登陆IP',
    Flogin_time    	datetime 		NOT NULL	COMMENT '用户最后登陆时间',
	Fpwd_mtime    	datetime 		default NULL	COMMENT '用户密码最后修改时间',
	Fpwd_ip			varchar(32) 	default NULL 	COMMENT '用户密码最后修改IP',
    Fpaypwd_mtime	datetime 		default NULL	COMMENT '用户支付密码最后修改时间',
    Fpaypwd_ip		varchar(32) 	default NULL 	COMMENT '用户支付密码最后修改IP',
    Fquestion1		varchar(255) 	default NULL 	COMMENT '用户问题1',
    Fanswer1		varchar(255) 	default NULL	COMMENT '用户答案1',    
	Fmemo        	varchar(128) 	default NULL,
	Fstandby1    	int    			default NULL,
	Fstandby2    	bigint    		default NULL,
	Fstandby3   	bigint 			default NULL,
	Fstandby4    	varchar(64)		default NULL,
	Fstandby5    	varchar(64)   	default NULL,
	Fstandby6    	varchar(255)   	default NULL,
    Fstandby7    	varchar(255)   	default NULL,
    Fstandby8    	varchar(255)   	default NULL,
    Fstandby9    	datetime		default NULL,
    Fstandby10   	datetime  		default NULL,
  PRIMARY KEY (`Fuid`),
  UNIQUE KEY `idx_username` (`Fuser_name`),
  KEY `idx_mobile` (`Fmobile`),
  KEY `idx_email` (`Femail`),
  KEY `idx_creid` (`Fcre_id`),
  KEY `idx_modifytime` (`Fmodify_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000000;
